name: ServerMinimap
main: de.craftlancer.serverminimap.ServerMinimap
version: 0.5.1
author: SydMontague
description: A serverside Minimap via maps.
permissions:
    minimap.fastupdate:
        description: Updates the minimap of the player much faster
        default: false
commands:
    waypoint:
        usage: /waypoint help
    minimap:
        usage: /minimap
        description: Gives you a minimap item
        