name: ServerMinimap
main: de.craftlancer.serverminimap.ServerMinimap
version: 0.4
author: SydMontague
description: POC
permissions:
    minimap.fastupdate:
        description: Updates the minimap of the player much faster
        default: false